### PR TITLE
aarch64: Use architecture specific header to general syscalls

### PR DESCRIPTION
**Pull request by alexmurray**
This ensures clone3, getrlimit and setrlimit are defined for aarch64 - also
update syscalls.csv from 5.6.0 to pick up these new syscalls

### CODE REVIEW

**Comment by jdstrand** [comment]
FYI, this is to address https://launchpad.net/bugs/1877633

**Comment by drakenclimber** [comment]
The changes look good to me.  I tested out the `getrlimit()` and `setrlimit()` changes on an arm64 box I had laying around.  I didn't test the `clone3()` change, but I see no issues there.

@alexmurray - could you please update the patch with your signed-off-by?  Thanks!

`Reviewed-by: Tom Hromatka <tom.hromatka@oracle.com>`

@pcmoore, I originally tagged this as v2.5, but I'm now second guessing myself and wondering if this deserves a v2.4.4 release of its own.  Thoughts?

**Comment by pcmoore** [comment]
Thanks @alexmurray for the fix, but as @drakenclimber already pointed out, please include your sign-off in the patch.  We've written up a guide to submitting patches in the [CONTRIBUTING.md](https://github.com/seccomp/libseccomp/blob/master/CONTRIBUTING.md) doc if that helps.

@drakenclimber, yes, I think we need this both for v2.5.0 and v.2.4.x.  Do you want to create a new issue for this for the v2.4.4 milestone?  We obviously can't backport this fix.

**Comment by drakenclimber** [comment]
Sure.  I can take care of the v2.4.4 side of things.

**Comment by alexmurray** [comment]
Apologies for missing CONTRIBUTING.md - have added my signed-off-by and Tom's reviewed-by. @drakenclimber I can try take a look at 2.4.4 if you need - let me know.

**Comment by drakenclimber** [comment]
> Apologies for missing CONTRIBUTING.md - have added my signed-off-by and Tom's reviewed-by. @drakenclimber I can try take a look at 2.4.4 if you need - let me know.

That would be really helpful :)!  Thanks.

**Comment by pcmoore** [comment]
Looks good to me, merged via 7780b0853eff8521bbf79611656c68fadc1dab3d - thanks everyone!

**Pull request closed without merging**
