### PR TITLE
RFE: improve the internal syscall tables (gperf,CSV)

### PR DESCRIPTION
**Pull request by pcmoore**
This PR is based heavily on the work of @giuseppe and PR #204.  I suggest reading through that PR first before looking at these patches.

In addition to splitting the initial monolithic patch into three (add the syscall CSV table, add gperf support, remove the old syscall tables), a number of other changes were made:
* Various style tweaks
* .gitignore fixes
* Dropped the arch-syscall-validate changes as they were masking other problems
* Fixed the x86, x32, ARM, all the MIPS ABIs, s390, and s390x ABIs as the syscall offsets were not properly incorporated into this change
* Cleaned up the ABI specific headers
* Cleaned up generate_syscalls_perf.sh and renamed to arch-gperf-generate
* Fixed problems with automake's file packaging

### CODE REVIEW

**Comment by pcmoore** [comment]
@giuseppe I hope this looks okay to you.  I left your name on the middle/gperf patch as I wanted you to get credit for all your work on this, but if you have a problem with that please let me know.

**Comment by drakenclimber** [comment]
The cleanup looks really good, @pcmoore .  I like the idea of using arch-syscall-validate to generate the csv file.  Good call.

For all of the patches:
`Reviewed-by: Tom Hromatka <tom.hromatka@gmail.com>`

**Comment by pcmoore** [comment]
> @pcmoore thanks for the changes
> 
> LGTM

Thanks for all of you work @giuseppe!  All I did was clean it up a bit and smooth out some rough edges.

**Comment by pcmoore** [comment]
> The cleanup looks really good, @pcmoore .

Thanks for the review.

> I like the idea of using arch-syscall-validate to generate the csv file. Good call.

Yes, this should make updating the syscall tables a trivial task.  We'll should be able to do much more frequent stable updates in the v2.5.x branch to catch new syscalls.

**Comment by pcmoore** [comment]
Merged at HEAD 4bd8de391d5920bdbdb639b1d81ddd7bfe4d7549.

**Comment by giuseppe** [comment]
@pcmoore there are a few changes (like the current PR), that would be nice to have in a release.  Is there any plan for cutting a new one?

**Comment by pcmoore** [comment]
We track our release progress using milestones, you are most likely interested in v2.5.0:

* https://github.com/seccomp/libseccomp/milestone/4

**Pull request closed without merging**
