### PR TITLE
BUG: avoid running live python tests in TravisCI

### PR DESCRIPTION
**Pull request by whereswaldon**
Not sure if this is *how* this should be achieved, but it was the most straightforward way that I could see to change the mode of the `./tests/regression` script from a `make` invocation. There didn't seem to be a way to supply flags directly, so I introduced this new environment variable. Feedback welcome!

`Signed-off-by: Chris Waldon <chris.waldon@ibm.com>`

### CODE REVIEW

**Comment by whereswaldon** [comment]
Hmm. The build still can't install `cython`. @drakenclimber @pcmoore Do you think the correct approach is to lock back to Python 3.8 like in #201, or something else?

**Comment by pcmoore** [comment]
I suspect you may need to remove the explicit python nightly dependency; you can try the code snippet from #199:
```
Author: Paul Moore <paul@paul-moore.com>
Date:   Wed Jan 8 00:47:03 2020 -0500

    travis: use the default Python version
    
    Signed-off-by: Paul Moore <paul@paul-moore.com>

diff --git a/.travis.yml b/.travis.yml
index da1cde5..723a885 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -16,8 +16,6 @@ compiler:
   - gcc
 
 language: python
-python:
-  - "nightly"
 
 addons:
   coverity_scan:
```

**Comment by drakenclimber** [comment]
The change looks reasonable to me.  Hopefully Paul's small addition will appease Travis, and then we can merge all of this in.

Thanks for the help!

**Comment by whereswaldon** [comment]
Sorry for the force-push! I realized that a commit that I made through the GitHub UI wasn't signed off, and I don't think you can amend commits through github.

**Comment by whereswaldon** [comment]
Also, @pcmoore you're welcome to make small tweaks like that directly on my branches in the future. This sat for so long because I thought you already had (just me misreading an email).

**Comment by pcmoore** [comment]
> Sorry for the force-push! I realized that a commit that I made through the GitHub UI wasn't signed off, and I don't think you can amend commits through github.

No problem, we're not too picky on stuff that happens in development forks/branches.  In fact, I generally dislike PRs with a pile of incorrect/broken patches which are fixed by later patches.  I'm a firm believer in *not* merging patches that are known to be problematic (it helps keep the tree sane, keeps "git bisect" useful, etc.).

> Also, @pcmoore you're welcome to make small tweaks like that directly on my branches in the future. This sat for so long because I thought you already had (just me misreading an email).

While I appreciate the vote of trust, I try to stay away from modifying other's work; it can get dicey for a variety of reasons.  You may see me make small style/formatting changes from time to time, but I try to stay away from substantive changes for a variety of reasons.

**Comment by pcmoore** [comment]
Merged into master via b9dddcc74ddabf6c281c9be44a9b0f8891ed7b45 and b4493a16c9408164f0a44614d42d25f76a192289.

Merged into release-2.4 via 3a6d076bf5d49d435fa8868d550c3f1668ef265c and c4901128e67458b6448ae310e5b9949697c3608e.

Thanks everyone!

**Pull request closed without merging**
