### PR TITLE
BUG: fix typo in seccomp_merge.3

### PR DESCRIPTION
**Pull request by lucab**
Minor typo fix: s/assocated/associated/

### CODE REVIEW

**Comment by pcmoore** [comment]
Thanks for the patch!  May I add your sign-off to the commit?

* https://github.com/seccomp/libseccomp/blob/master/SUBMITTING_PATCHES

**Comment by lucab** [comment]
I'm not sure I understand your question. The commit is already signed-off (and gpg-signed) since the beginning. Do you mean signing-off the PR message?

**Comment by pcmoore** [comment]
Sorry, for some reason I missed your sign-off when I first looked at the PR.  It looks like we are all set, sorry for the confusion.

**Comment by pcmoore** [comment]
Merged in 4371bf04c75780457b192e4defd2f8d4e5d61f27, thanks.

**Pull request closed without merging**
