### PR TITLE
RFE: integrate codespell into our syntax checker

### PR DESCRIPTION
**Pull request by pcmoore**
This is a low priority, and far from perfect item, but I think it would be nice to have to help improve code quality/readability.  The one draback is that it adds another dependency to the "./tools/check-syntax" script, but the `codespell` tool seems to be readily available in most distros I believe.

### CODE REVIEW

**Comment by drakenclimber** [comment]
Nifty.  I added some typos to my source code and it made sane suggestions.  And it ignored completely garbage variable names like `asldraesoiurlkj` as well.

The only minor complaint I have is that it's rather slow to run.  Previously `make check-syntax` took ~3 seconds to run on my machine.  Now it takes ~1 minute.  But I think that's a small price if it ends up helping.

Thanks!

`Reviewed-by: Tom Hromatka <tom.hromatka@oracle.com>`

**Comment by pcmoore** [comment]
> The only minor complaint I have is that it's rather slow to run. Previously make check-syntax took ~3 seconds to run on my machine. Now it takes ~1 minute. But I think that's a small price if it ends up helping.

Huh, that's slightly worrying.  On my laptop (a Lenovo X1) I'm seeing \~24s to run `./tools/check-syntax`; I'm confused why you are seeing a 2x~3x slowdown.  Can you try it again and confirm the one minute runtime?

```
% time ./tools/check-syntax 
=============== Tue Sep  1 11:35:11 AM EDT 2020 ===============
Code Syntax Check Results ("check-syntax ")
...
============================================================

real    0m23.780s
user    0m21.655s
sys     0m3.176s
```

**Comment by drakenclimber** [comment]
I killed slack, zoom, and all of the other various hogs on my system.  I have a Lenovo T490 with an Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz.

On upstream master of libseccomp:
```
$ time make check-syntax
...
============================================================

real	0m1.277s
user	0m0.792s
sys	0m0.771s
```

On the working `pcmoore-codespell` branch:
```
$ time make check-syntax
...
============================================================

real	0m45.098s
user	0m40.375s
sys	0m4.699s
```

Looks like slack and other things were slowing me down quite a bit, but it's still pretty slow on my machine.  The results were nearly identical when I bypassed make and ran `./tools/check-syntax` directly.

**Comment by pcmoore** [comment]
> I killed slack, zoom, and all of the other various hogs on my system. I have a Lenovo T490 with an Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz.

According to `lscpu` it looks like my machine has a "Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz"; I'm not enough of a hardware geek to know if those two CPUs are comparable, but I'm going to guess they are close enough.  Maybe the issue is I/O?  Although considering the limited number of files, sizes, etc. I imagine most of these should be easily cached.

/me shrugs

Regardless, I agree with your comments above that the slowdown is worth the additional checks so I'm going to go ahead and merge this - thanks for the review!

**Pull request merged**
