### PR TITLE
RFE: add support for io-uring related system calls in kernel 5.1

### PR DESCRIPTION
**Pull request by omegacoleman**
This patch adds support for the newly-introduced io-uring system calls
in kernel 5.1, for description with io-uring, see:
https://lwn.net/ml/linux-fsdevel/20190112213011.1439-1-axboe@kernel.dk/

I was doing this because this enables us to configure and enable it in docker (opencontainer/runc in paticular) without disabling seccomp.

Signed-off-by: Stephen Coleman <omegacoleman@gmail.com>

### CODE REVIEW

**Comment by pcmoore** [comment]
This looks okay to me, if it looks good to @drakenclimber too I think we can get this merged.

**Comment by drakenclimber** [comment]
Looks good to me.  I compared the values by hand and also ran the patch through arch-syscall-validate.

`Reviewed-by: Tom Hromatka <tom.hromatka@oracle.com>`

**Comment by pcmoore** [comment]
Merged via 5fc22428507ecea00ee9e2215d972777da9a99b6, thanks!

**Comment by omegacoleman** [comment]
good to hear

**Pull request closed without merging**
