### PR TITLE
BUG: add ipc and socket multiplexing support to ppc64

### PR DESCRIPTION
**Pull request by drakenclimber**
I was able to get some time on a ppc64le box, so I fixed the ppc64 multiplexing and munging of the ipc syscalls.  Like s390, ppc64 doesn't support `semop()`

Note that this branch has a commit (enable ppc64 on travis) that should not be committed.

### CODE REVIEW

**Comment by pcmoore** [comment]
> Note that this branch has a commit (enable ppc64 on travis) that should not be committed.

There is no harm in fixing up the Travis CI patch and submitting it via this PR, we can just drop the other PR.

**Comment by pcmoore** [comment]
Two quick takes on this patch:
* We are clearly missing some test coverage somewhere, we likely already have the test written we just need to add ppc64le to the test.
* A terrible thought just occurred to me: even though ppc64[le] has support for direct-wired syscalls long before seccomp-bpf was added, the kernel still supports the socketcall() syscall, right?  This means we still need to add the socket munging as well as the kernel still has the older multiplexed API available.

**Comment by drakenclimber** [comment]
>we likely already have the test written we just need to add ppc64le to the test.

Yeah, coveralls sent me a nastygram about the drop in coverage.  I'll address that.

> the kernel still supports the socketcall() syscall, right?

Yes, socketcall() is syscall 102 on PPC. I _think_ I have that fully covered in this patch - I added both munge functions for name/num as well as the mux/demux functions for the syscalls.

> There is no harm in fixing up the Travis CI patch and submitting it via this PR, we can just drop the other PR.

Sounds good.  I'll make the travis ci commit comment correct and add it to this patchset.

**Comment by drakenclimber** [comment]
> > Yes, socketcall() is syscall 102 on PPC. I think I have that fully covered in this patch - I added both munge functions for name/num as well as the mux/demux functions for the syscalls.
> 
> I don't see the socketcall() related syscalls in the munge functions ... ?

Sorry I still had ipc on my mind.  Oi.

I'm cool with adding the socket syscalls as well.  Looks like I should add ppc64le to test #30 also.

**Comment by pcmoore** [comment]
Just checking in @drakenclimber, I see some code updates to this PR but not comments here, is this ready for further review or are you still playing with it?

**Comment by drakenclimber** [comment]
> Just checking in @drakenclimber, I see some code updates to this PR but not comments here, is this ready for further review or are you still playing with it?

Yes, I believe this is now ready to go.  Both IPC and socket calls now appear to be fully support on ppc64

**Comment by pcmoore** [comment]
Sweet, go ahead and merge those patches!
```
Acked-by: Paul Moore <paul@paul-moore.com>
```

**Pull request merged**
