### PR TITLE
RFE: update the internal syscall tables to Linux v5.4-rc4

### PR DESCRIPTION
**Pull request by pcmoore**
This is long overdue so quite a few changes, including tweaks to
support some newly direct wired syscalls which were previously
multiplexed.

We really need to make sure we update the syscall table more often.

Signed-off-by: Paul Moore <paul@paul-moore.com>

### CODE REVIEW

**Comment by pcmoore** [comment]
Fixes #164.

**Comment by drakenclimber** [comment]
I had to make a couple nickle-and-dime changes (1 - backport Stéphane's fix and 2 - fix a small oops in the tools/Makefile.am) to run `make distcheck`, but it ran successfully.

```
$ git diff
diff --git a/include/Makefile.am b/include/Makefile.am
index ba3723f..d996128 100644
--- a/include/Makefile.am
+++ b/include/Makefile.am
@@ -16,4 +16,4 @@
 # along with this library; if not, see <http://www.gnu.org/licenses>.
 #
 
-include_HEADERS = seccomp.h
+include_HEADERS = seccomp.h seccomp-syscalls.h
diff --git a/tools/Makefile.am b/tools/Makefile.am
index f768365..34f374f 100644
--- a/tools/Makefile.am
+++ b/tools/Makefile.am
@@ -16,7 +16,7 @@
 # along with this library; if not, see <http://www.gnu.org/licenses>.
 #
 
-AM_CPPFLAGS = -I${top_builddir}/include
+#AM_CPPFLAGS = -I${top_builddir}/include
 
 noinst_LTLIBRARIES = util.la
```

**Comment by drakenclimber** [comment]
./arch-syscall-validate threw this minor diff which I think we should clean up sometime, but it shouldn't affect this patchset.

```
--- mips [library]
+++ mips [system]
@@ -1,3 +1,13 @@
+  SYSTBL  arch/mips/include/generated/asm/syscall_table_32_o32.h
+  SYSTBL  arch/mips/include/generated/asm/syscall_table_64_n32.h
+  SYSTBL  arch/mips/include/generated/asm/syscall_table_64_n64.h
+  SYSTBL  arch/mips/include/generated/asm/syscall_table_64_o32.h
+  SYSHDR  arch/mips/include/generated/uapi/asm/unistd_n32.h
+  SYSHDR  arch/mips/include/generated/uapi/asm/unistd_n64.h
+  SYSHDR  arch/mips/include/generated/uapi/asm/unistd_o32.h
+  SYSNR  arch/mips/include/generated/uapi/asm/unistd_nr_n32.h
+  SYSNR  arch/mips/include/generated/uapi/asm/unistd_nr_n64.h
+  SYSNR  arch/mips/include/generated/uapi/asm/unistd_nr_o32.h
 accept 168
 accept4        334
 access 33
```

**Comment by pcmoore** [comment]
> ./arch-syscall-validate threw this minor diff which I think we should clean up sometime, but it shouldn't affect this patchset.

Hmm, WORKSFORME?  @drakenclimber if you can reproduce this on your system, please create an issue for this so we can dig into it and resolve it.

```
# (cd ~/sources/linux/linux-linus; git show)
commit 7d194c2100ad2a6dded545887d02754948ca5241 (HEAD -> master, tag: v5.4-rc4, linus/master, linus/HEAD)
Author: Linus Torvalds <torvalds@linux-foundation.org>
Date:   Sun Oct 20 15:56:22 2019 -0400

    Linux 5.4-rc4

diff --git a/Makefile b/Makefile
index 19efe04b398c..5475cdb6d57d 100644
--- a/Makefile
+++ b/Makefile
@@ -2,7 +2,7 @@
 VERSION = 5
 PATCHLEVEL = 4
 SUBLEVEL = 0
-EXTRAVERSION = -rc3
+EXTRAVERSION = -rc4
 NAME = Nesting Opossum
 
 # *DOCUMENTATION*
# make check-build
 ...
# cd src/
# ./arch-syscall-validate ~/sources/linux/linux-linus
# echo $?
0
#
```

**Comment by drakenclimber** [comment]
> Hmm, WORKSFORME? @drakenclimber if you can reproduce this on your system, please create an issue for this so we can dig into it and resolve it.

Yeah, I can reproduce it at will on my system.  I followed the same steps you outlined above.  I jump around on different kernels quite a bit, and I am seeing this on an old(ish) Oracle Linux setup.

I filed Bug #178, and I figured out how to reproduce it.  When I get a chance I'll try on a different system.

**Comment by drakenclimber** [comment]
Yep, this looks good to go.  Thanks for picking this up.

`Acked-by: Tom Hromatka <tom.hromatka@oracle.com>`

**Comment by pcmoore** [comment]
Merged into master, thanks for the quick review.

**Pull request closed without merging**
