### PR TITLE
RFE: add a section on release tarball signatures to README.md

### PR DESCRIPTION
**Pull request by pcmoore**
Signed-off-by: Paul Moore <paul@paul-moore.com>

### CODE REVIEW

**Comment by drakenclimber** [comment]
Looks good.

`Reviewed-by: Tom Hromatka <tom.hromatka@oracle.com>`

**Comment by pcmoore** [comment]
Merged via e5c4b5ee8086b936d28b080e5477950f632b4d43 into master and ea4dafc0f45d859f4ff157f1120e77d0f01f5473 into release-2.4.

**Comment by pcmoore** [comment]
@drakenclimber instead of making release-X.Y backports a separate process, I'm thinking we should just have a discussion about the backport when we merge the PR/patch into master.  If we agree that it should be backported, let's just do it right then.

Thoughts?

**Comment by drakenclimber** [comment]
I really like that idea.  Spreads the workload out throughout the release cycle rather than piling it on all at the end.

We just need to remember to do it every time a patch comes in :)

**Comment by pcmoore** [comment]
> I really like that idea. Spreads the workload out throughout the release cycle rather than piling it on all at the end.

Cool, let's do that for here on out.  If we are reviewing a patch and we think it should be backported to a release-X.Y branch, let's call it out in the PR comments.

> We just need to remember to do it every time a patch comes in :)

Well, no one ever said this job was easy ;)

**Comment by drakenclimber** [comment]
One slight disappointment with the github interface - I can add an issue to v2.5 or v2.4.3, but not both.  I was hoping to use that as one way to ensure issues are backported as necessary.

**Comment by pcmoore** [comment]
Yeah, I had that same idea at one point in time and ran into the same disappointment :(

**Pull request closed without merging**
