### PR TITLE
RFE: update syscall table to v5.12-rc7

### PR DESCRIPTION
**Pull request by pcmoore**
A routine update of the syscall table to v5.12-rc7.  This needs to be merged into the main branch as well as backported into the release-2.5 branch.

### CODE REVIEW

**Comment by pcmoore** [comment]
> ... backported into the release-2.5 branch.

Actually, the entire "src/syscalls.csv" file should be copied from the main branch into the release-2.5 branch.

**Comment by pcmoore** [comment]
> Actually, the entire "src/syscalls.csv" file should be copied from the main branch into the release-2.5 branch.

Nevermind, that fails miserably due to the extra ABIs in main.  It looks like the best approach is just to regenerate the syscall table in the release-2.5 branch.  I'll send a separate PR for that.

**Comment by pcmoore** [comment]
I also added a patch to fix the missing `faccessat2()` defines mentioned in issue #314.

**Review by drakenclimber — APPROVED** [review]
Looks good to me.  Thanks, @pcmoore 

`Reviewed-by: Tom Hromatka <tom.hromatka@oracle.com>`

**Comment by pcmoore** [comment]
Merged at de60727c86e5946521b17763edb5ec344fc43da4, closing.

**Pull request closed without merging**
