### PR TITLE
RFE: Add parisc64 support to 2.4 branch

### PR DESCRIPTION
**Pull request by drakenclimber**
I have mixed feelings on this pull request.

Reasons to add this patchset to the v2.4.4 release:
- The parisc syscall tables are significantly out of date
- Our automated tools (arch-syscall-validate, etc.) are very good and should catch most errors

Reasons not to add this patchset:
- The parisc syscall table has been out of date for a long time and no one has objected yet
- Higher risk than I would like

@pcmoore, @hdeller, and the community as a whole, do you have an opinion?

As of right now, I am leaning toward rejecting this patchset for v2.4.4.  parisc users can use v2.5.x now that it's released.

### CODE REVIEW

**Comment by drakenclimber** [comment]
Also see pull request #276 since it updates arch-syscall-validate to verify the parisc syscall table.

**Comment by drakenclimber** [comment]
Finally, note that the automated tests will currently fail because I haven't updated the syscall tables of all the other architectures yet.  I will send that out for review soon.

**Comment by hdeller** [comment]
There is no need to pull in a "parisc64" syscall table (as long as the 32bit parisc table stays), because there isn't any 64bit userspace yet for parisc. On parisc we currently only have a 32bit userspace, running either on a 32bit kernel or on a 64bit kernel - depending on the physical machine.
So, from my point of view I don't see any urgency to pull "parisc64" changes it into existing branches.

**Comment by hdeller** [comment]
Regarding the statement: "... v2.4.4 release: The parisc syscall tables are significantly out of date".
The newly added syscalls which are missing in the v2.4.4 release actually are:
+437    common  openat2                         sys_openat2
+438    common  pidfd_getfd                     sys_pidfd_getfd
+439    common  faccessat2                      sys_faccessat2
Do you want me to create a pull request for those?
Helge

**Comment by drakenclimber** [comment]
> There is no need to pull in a "parisc64" syscall table (as long as the 32bit parisc table stays), because there isn't any 64bit userspace yet for parisc. On parisc we currently only have a 32bit userspace, running either on a 32bit kernel or on a 64bit kernel - depending on the physical machine.
> So, from my point of view I don't see any urgency to pull "parisc64" changes it into existing branches.

Thank you.  That clarifies things greatly.


> Regarding the statement: "... v2.4.4 release: The parisc syscall tables are significantly out of date".
> The newly added syscalls which are missing in the v2.4.4 release actually are:
> +437 common openat2 sys_openat2
> +438 common pidfd_getfd sys_pidfd_getfd
> +439 common faccessat2 sys_faccessat2
> Do you want me to create a pull request for those?

Thanks so much for the kind offer, but I think I have it ready to go [here](https://github.com/drakenclimber/libseccomp/commit/212f1bc3922ab085dc78d0ab9151943fb00a4c9e).  Note that when I ran parisc through our syscall checker, it found [several more differences](https://github.com/drakenclimber/libseccomp/commit/212f1bc3922ab085dc78d0ab9151943fb00a4c9e#diff-60c7603b14c0948d558a99ea3cc01155L13) than the ones you cited above.  Is this correct?

To run the validation script that generated these diffs:
```
git clone https://github.com/drakenclimber/libseccomp.git
cd libseccomp
git checkout wip/release-2.4.4
./autogen.sh && ./configure && make check-build
cd src
./arch-syscall-validate <path-to-Linus'-latest kernel> | less
```

**Comment by drakenclimber** [comment]
> To run the validation script that generated these diffs:
> 
> ```
> git clone https://github.com/drakenclimber/libseccomp.git
> cd libseccomp
> git checkout wip/release-2.4.4
> ./autogen.sh && ./configure && make check-build
> cd src
> ./arch-syscall-validate <path-to-Linus'-latest kernel> | less
> ```

And of course you'll need to revert the arch-parisc-syscalls.c file to see the diffs. :)

**Comment by hdeller** [comment]
On 29.07.20 00:26, Tom Hromatka wrote:
>> Do you want me to create a pull request for those?
>
> Thanks so much for the kind offer, but I think I have it ready to go here. Note that when I ran parisc through our syscall checker, it found several more differences than the ones you cited above. Is this correct?

I ran the validation script and your changes look all correct.
Thank you!

Helge

**Comment by drakenclimber** [comment]
Thanks so much for the help, @hdeller.  I'm going to close this pull request (without merging it), and I'll open a new one for the updated syscall tables.

**Pull request closed without merging**
