### PR TITLE
RFE: add the statx syscall

### LINKED ISSUE #88: RFE: new syscall statx
There is a new syscall: statx

https://github.com/torvalds/linux/blob/master/arch/x86/entry/syscalls/syscall_64.tbl

### PR DESCRIPTION
**Pull request by tklauser**
Fixes #88

Signed-off-by: Tobias Klauser <tklauser@distanz.ch>

### CODE REVIEW

**Comment by antonio-rojas** [comment]
Any chance this could get higher priority? Not having this breaks Qt in systemd containers: Qt 5.10 makes extensive use of statx on supported kernels, and systemd 235 will automatically block syscalls not known by libseccomp in containers.

**Comment by pcmoore** [comment]
I bumped the priority up to "medium".  I had hoped to have another libseccomp minor release out by now, but I wanted to resolve at least one other bug that had been annoying me and unfortunately I keep getting distracted.  Perhaps I can just do another micro/patch level release to update the syscall table ... I'll revisit this in a few days to see if I've got any chance of resolving the other bug any time soon.

**Comment by justincormack** [comment]
It might make sense to update the comment to `based on Linux 4.14` rather than `based on Linux 4.14-rc5+` as 4.14 final is out (and there were no more syscalls added). As 4.14 is the new LTS kernel it would be nice to have a release out with this soon.

**Comment by tklauser** [comment]
@justincormack thanks for the suggestion, will update the comments accordingly.

**Comment by pcmoore** [comment]
@tklauser @justincormack considering we are at 4.15-rc6, I would probably just prefer to see the syscall list updated to reflect 4.15-rc6 as it is unlikely we will see any significant syscall related changes at this point in 4.15.

Also, if you update your PR/patches, please make sure you any/all new syscalls, not just statx().  Thanks!

**Comment by justincormack** [comment]
There are no syscalls since `statx` in 4.15 either, conveniently.

**Comment by tklauser** [comment]
@pcmoore Ok. So I guess it's fine to just update the comment to say "based on Linux 4.15", assuming it will be released within the next few weeks. And as @justincormack already noted, there were no additional syscalls added (besides `statx`) to neither 4.14 nor 4.15, so no further additions needed there.

**Comment by pcmoore** [comment]
I'm reviewing and merging this now, but I noticed you forgot the X32_SYSCALL_BIT in the x32 statx() definition.  I'll fix that up during the merge, but just a FYI for the future.

**Comment by pcmoore** [comment]
Another note, it turns out there are other syscall changes in v4.15-rc7, I'll take care of those in a separate patch.

**Comment by pcmoore** [comment]
Merged via 4793ea990ea80ee26ed63e2a20723fdb417abf5b.

**Pull request closed without merging**
