### PR TITLE
RFE: add SuperH 32-bit support

### PR DESCRIPTION
**Pull request by glaubitz**
This is my first draft for adding architecture support for the SuperH architecture to libseccomp.

SuperH has supported seccomp since 2.6.27-rc2 (https://github.com/torvalds/linux/commit/c4637d475170ca0d99973efd07df727012db6cd1), but it seems support in libseccomp for SuperH was never added.

I have made the changes based on the code for other architectures like PA-RISC or PowerPC and I think most changes should be okay.

However, I have not figured out yet what needs to be done in order to update ```src/syscalls.csv```, maybe someone can help me with that.

SuperH support in the kernel is actively maintained and new hardware is being developed in the form of the J-Core architecture which is a binary-compatible, open source implementation of SuperH (see: https://j-core.org/).

### CODE REVIEW

**Comment by pcmoore** [comment]
Hi @glaubitz, thanks for the PR!  It's always nice to be able to add a new architecture to libseccomp, unfortunately it doesn't look like the current mainline Linux kernel support the seccomp BPF filtering capability necessary for libseccomp support.

The libseccomp filters rely on "mode 2" seccomp as opposed to the original seccomp implementation.  The original seccomp kernel implementation was a simplistic static list of syscalls allowed by the kernel, it was the second implementation, aka "mode 2", which implemented the ability to load BPF syscall filters into the kernel at runtime.  Unfortunately, some architecture specific changes are needed to support "mode 2" and not all architectures have made these changes, SuperH appears to be one of these architectures (look for `HAVE_ARCH_SECCOMP_FILTER` in the Kconfig files).

Have you looked into adding the necessary kernel support?

**Comment by glaubitz** [comment]
Hi Paul! Thanks for the hints and the explanation. I will look into adding the missing pieces into the kernel in coordination with the SuperH arch kernel maintainer.

**Comment by pcmoore** [comment]
That sounds good @glaubitz, thanks!

Since there is not well defined timeline for when the kernel support will land, I'm going to close this PR in favor of issue #272.   Please don't take this as negative commentary on this work (we are happy to add new arches!), I'm just trying to limit the number of long standing open PRs we have.

**Comment by glaubitz** [comment]
@pcmoore We have implemented SECCOMP_FILTER for SH now, it will be posted shortly to the LKML. Hope to be able to get it merged for 5.9.

**Comment by glaubitz** [comment]
Patches have been posted now:

> https://marc.info/?l=linux-sh&m=159546012829987&w=2
> https://marc.info/?l=linux-sh&m=159546012829985&w=2
> https://marc.info/?l=linux-sh&m=159546012829989&w=2
> https://marc.info/?l=linux-sh&m=159546012929991&w=2

libseccomp live tests pass as expected.

OK to open a new PR?

**Comment by pcmoore** [comment]
I would recommend waiting until the patches have been merged into Linus' tree.

**Comment by glaubitz** [comment]
The patch is now in linux-next (https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=469023465e7995ed50de6ebaaa5942dd67d0f3bf).

OK to open the PR now or shall we wait for Linus to pull in linux-next?

**Comment by pcmoore** [comment]
I would recommend waiting until the patches have been merged into Linus' tree.

**Pull request closed without merging**
