### PR TITLE
BUG: fix document typo in "Berkeley"

### PR DESCRIPTION
**Pull request by ferivoz**
Signed-off-by: Samanta Navarro <ferivoz@riseup.net>

### CODE REVIEW

**Comment by drakenclimber** [comment]
Looks good to me.

`Acked-by: Tom Hromatka <tom.hromatka@oracle.com>`

**Comment by pcmoore** [comment]
Thanks @ferivoz!

```
Acked-by: Paul Moore <paul@paul-moore.com>
```

**Comment by pcmoore** [comment]
Since I'm the last one to ACK this patch, I'll go ahead and merge it as soon as I'm on the right system.

**Comment by pcmoore** [comment]
Merged via ff6923163174ed156c4c0645961e602396298df9 and d9cdb27c45dd9c1efbf9246533c58e07c0032162, thanks!

**Pull request closed without merging**
