### PR TITLE
RFE: update Travis to build on s390x

### PR DESCRIPTION
**Pull request by AnitaNayak**

### CODE REVIEW

**Comment by pcmoore** [comment]
Hi @AnitaNayak, thanks for the patch.  Unfortunately, it appears your patch is against the release-2.3 branch which is no longer supported upstream, could you rebase and test your patch against the master branch?

Also, I tried enabling aarch64 builds in Travis a month (or two?) ago and ran into failures with some fo the dependencies; have you been able to get it to work with s390x?

**Comment by AnitaNayak** [comment]
Apology for the late reply. Will try with master branch.

**Comment by pcmoore** [comment]
No worries on the delay, let us know how it goes.

**Comment by pcmoore** [comment]
This looks to be superseded by #194, closing this PR.

**Pull request closed without merging**
