### PR TITLE
RFE: add the SCMP_FLTATR_CTL_WAITKILL filter attribute

### LINKED ISSUE #387: RFE: add support for SECCOMP_FILTER_FLAG_WAIT_KILLABLE_RECV (Linux 5.19)
Linux 5.19 introduced a new seccomp flag: SECCOMP_FILTER_FLAG_WAIT_KILLABLE_RECV
https://github.com/torvalds/linux/commit/c2aa2dfef243

I would like to use it to handle notification from Golang programs which are often preempted by the runtime with SIGURG.

Related issues in other projects:
- https://github.com/libseccomp-rs/libseccomp-rs/issues/142
- https://github.com/opencontainers/runtime-spec/pull/1161
- https://github.com/kubernetes-sigs/security-profiles-operator/pull/1201
- https://github.com/containers/crun/pull/1008

cc @rata

### PR DESCRIPTION
**Pull request by pcmoore**
The SCMP_FLTATR_CTL_WAITKILL attribute requests that the SECCOMP_FILTER_FLAG_WAIT_KILLABLE_RECV flag be passed to the seccomp(2) system call when possible, which is currently only when the SECCOMP_FILTER_FLAG_NEW_LISTENER flag is also set.

Resolves #387

### CODE REVIEW

**Review by drakenclimber — APPROVED** [review]
Looks good to me.

`Acked-by: Tom Hromatka <tom.hromatka@oracle.com>`

**Comment by drakenclimber** [comment]
Thanks, @pcmoore

**Comment by drakenclimber** [comment]
Pushed to main in commit 96989965042a.  Thanks, @pcmoore

**Comment by pcmoore** [comment]
Thanks @drakenclimber, I've had limited network access the past few weeks but things should be getting back to normal next week ... once I get caught up ;)

**Comment by drakenclimber** [comment]
> Thanks @drakenclimber, I've had limited network access the past few weeks but things should be getting back to normal next week ... once I get caught up ;)

@pcmoore, No worries.  Let me know if you need any help or there's anything you want me to pick up.

**Pull request closed without merging**
