### PR TITLE
BUG: Issues/148v4

### PR DESCRIPTION
**Pull request by drakenclimber**
Changes from v3 to v4:

- Simplified the accumulator comparison logic to be closer to v2 of this pull request

I also had a chance to run more tests including the binary tree changes (which were prone to hash collisions) against this patchset.  The binary tree tests passed.

I think we're good to go.

### CODE REVIEW

**Comment by pcmoore** [comment]
This looks good to me, but there is a python test failure on my system:
```
./regression -m c -m python -b 50-sim-hash_collision
=============== Tue Apr 16 12:42:49 EDT 2019 ===============
Regression Test Report ("regression -m c -m python -b 50-sim-hash_collision")
 batch name: 50-sim-hash_collision
 test mode:  c
 test type:  bpf-sim
Test 50-sim-hash_collision%%001-00001 result:   SUCCESS
Test 50-sim-hash_collision%%002-00001 result:   SUCCESS
Test 50-sim-hash_collision%%003-00001 result:   SUCCESS
Test 50-sim-hash_collision%%004-00001 result:   SUCCESS
Test 50-sim-hash_collision%%005-00001 result:   SUCCESS
Test 50-sim-hash_collision%%006-00001 result:   SUCCESS
Test 50-sim-hash_collision%%007-00001 result:   SUCCESS
Test 50-sim-hash_collision%%008-00001 result:   SUCCESS
 batch name: 50-sim-hash_collision
 test mode:  python
 test type:  bpf-sim
Test 50-sim-hash_collision%%001-00001 result:   FAILURE bpf_sim resulted in ERRNO(100)
Test 50-sim-hash_collision%%002-00001 result:   SUCCESS
Test 50-sim-hash_collision%%003-00001 result:   SUCCESS
Test 50-sim-hash_collision%%004-00001 result:   SUCCESS
Test 50-sim-hash_collision%%005-00001 result:   SUCCESS
Test 50-sim-hash_collision%%006-00001 result:   SUCCESS
Test 50-sim-hash_collision%%007-00001 result:   SUCCESS
Test 50-sim-hash_collision%%008-00001 result:   SUCCESS
Regression Test Summary
 tests run: 16
 tests skipped: 0
 tests passed: 15
 tests failed: 1
 tests errored: 0
============================================================
```

**Comment by pcmoore** [comment]
Hmm.  Comparing the PFC and BPF output of the C and Python tests reveals identical output (as one would expect):
```
# PYTHONPATH=../src/python/build/lib.linux-x86_64-3.7:. python ./50-sim-hash_collision.py -b > 50.py.bpf 
# PYTHONPATH=../src/python/build/lib.linux-x86_64-3.7:. python ./50-sim-hash_collision.py -p > 50.py.pfc
# ./50-sim-hash_collision -b > 50.c.bpf
# ./50-sim-hash_collision -p > 50.c.pfc
# md5sum 50.c.bpf 50.py.bpf
55b4ba0b21d439caa55b8dc3be76d288  50.c.bpf
55b4ba0b21d439caa55b8dc3be76d288  50.py.bpf
# md5sum 50.c.pfc 50.py.pfc
3e5914f8ea7ba4ab8812dd779c70b6ab  50.c.pfc
3e5914f8ea7ba4ab8812dd779c70b6ab  50.py.pfc
```

**Comment by drakenclimber** [comment]
Weird.  It's also failing for me in the same spot.  Hmmm...

**Comment by drakenclimber** [comment]
But it succeeded on TravisCI.

```
 batch name: 50-sim-hash_collision
 test mode:  python
 test type:  bpf-sim
Test 50-sim-hash_collision%%001-00001 result:   SUCCESS
Test 50-sim-hash_collision%%002-00001 result:   SUCCESS
Test 50-sim-hash_collision%%003-00001 result:   SUCCESS
Test 50-sim-hash_collision%%004-00001 result:   SUCCESS
Test 50-sim-hash_collision%%005-00001 result:   SUCCESS
Test 50-sim-hash_collision%%006-00001 result:   SUCCESS
Test 50-sim-hash_collision%%007-00001 result:   SUCCESS
Test 50-sim-hash_collision%%008-00001 result:   SUCCESS
```

**Comment by pcmoore** [comment]
I'm not sure if this matters, especially since the BPF is the same on my system (?!), but Travis is using a different version of Python from what I'm using:
* Travis
```
$ python --version
Python 3.8.0a3+
```
* My system
```
# python --version
Python 3.7.3
```

What is on your system @drakenclimber?

**Comment by drakenclimber** [comment]
```
$ python --version
Python 2.7.5
```

**Comment by pcmoore** [comment]
Oh come on ... I go to debug this a bit further and now it is working:
```
# ./regression -m c -m python -b 50-sim-hash_collision
=============== Tue Apr 16 17:33:07 EDT 2019 ===============
Regression Test Report ("regression -m c -m python -b 50-sim-hash_collision")
 batch name: 50-sim-hash_collision
 test mode:  c
 test type:  bpf-sim
Test 50-sim-hash_collision%%001-00001 result:   SUCCESS
Test 50-sim-hash_collision%%002-00001 result:   SUCCESS
Test 50-sim-hash_collision%%003-00001 result:   SUCCESS
Test 50-sim-hash_collision%%004-00001 result:   SUCCESS
Test 50-sim-hash_collision%%005-00001 result:   SUCCESS
Test 50-sim-hash_collision%%006-00001 result:   SUCCESS
Test 50-sim-hash_collision%%007-00001 result:   SUCCESS
Test 50-sim-hash_collision%%008-00001 result:   SUCCESS
 batch name: 50-sim-hash_collision
 test mode:  python
 test type:  bpf-sim
Test 50-sim-hash_collision%%001-00001 result:   SUCCESS
Test 50-sim-hash_collision%%002-00001 result:   SUCCESS
Test 50-sim-hash_collision%%003-00001 result:   SUCCESS
Test 50-sim-hash_collision%%004-00001 result:   SUCCESS
Test 50-sim-hash_collision%%005-00001 result:   SUCCESS
Test 50-sim-hash_collision%%006-00001 result:   SUCCESS
Test 50-sim-hash_collision%%007-00001 result:   SUCCESS
Test 50-sim-hash_collision%%008-00001 result:   SUCCESS
Regression Test Summary
 tests run: 16
 tests skipped: 0
 tests passed: 16
 tests failed: 0
 tests errored: 0
============================================================
```

**Comment by drakenclimber** [comment]
Well mine is still failing if that makes you feel any better

**Comment by pcmoore** [comment]
> Well mine is still failing if that makes you feel any better

Sigh.  I've had my running in a loop without failure for the past ~20 minutes.  This combined with the identical BPF/PFC output has me at a loss; the only thing I can think of is some undefined behavior problem.  I was thinking it might be a problem with hashing an unpacked acc_state structure, but it looks like all of those are allocated (via the bpf_blk allocation) using zmalloc() so we shouldn't have a problem there.

@drakenclimber since you are able to reproduce this I'll leave this up to you for now.  I'll be very curious to hear what you find.

**Comment by drakenclimber** [comment]
> since you are able to reproduce this I'll leave this up to you for now. I'll be very curious to hear what you find.

Thanks ;).  I admit that I am rather stumped at the moment.  Hopefully a new day will produce some fresh ideas.  Your idea of an uninitialized value does some promising, though

**Comment by drakenclimber** [comment]
I was able to verify that the failing python code is still experiencing a hash collision.  Don't know why yet.

```
 line  OP   JT   JF   K
=================================
 0000: 0x20 0x00 0x00 0x00000004   ld  $data[4]

### x86_64
 0001: 0x15 0x00 0x1c 0xc000003e   jeq 3221225534 true:0002 false:0030
 0002: 0x20 0x00 0x00 0x00000000   ld  $data[0]
 0003: 0x35 0x00 0x01 0x40000000   jge 1073741824 true:0004 false:0005
 0004: 0x15 0x00 0x19 0xffffffff   jeq 4294967295 true:0005 false:0030

### syscall 1000
 0005: 0x15 0x00 0x04 0x000003e8   jeq 1000 true:0006 false:0010

### arg0
 0006: 0x20 0x00 0x00 0x00000014   ld  $data[20]
 0007: 0x15 0x00 0x14 0x00000000   jeq 0    true:0008 false:0028
 0008: 0x20 0x00 0x00 0x00000010   ld  $data[16]
 0009: 0x15 0x13 0x0f 0x00000002   jeq 2    true:0029 false:0025

### where did arg0 == 1 go?  It must have had a hash collision with
### syscall 1001.  Hmmm...

 0010: 0x15 0x00 0x11 0x000003e9   jeq 1001 true:0011 false:0028
 0011: 0x20 0x00 0x00 0x00000014   ld  $data[20]
 0012: 0x15 0x00 0x0f 0x00000000   jeq 0    true:0013 false:0028
 0013: 0x20 0x00 0x00 0x00000010   ld  $data[16]
 0014: 0x15 0x00 0x0d 0x00000001   jeq 1    true:0015 false:0028
 0015: 0x20 0x00 0x00 0x0000001c   ld  $data[28]
 0016: 0x54 0x00 0x00 0x00000000   and 0x00000000
 0017: 0x15 0x00 0x0a 0x00000000   jeq 0    true:0018 false:0028
 0018: 0x20 0x00 0x00 0x00000018   ld  $data[24]
 0019: 0x54 0x00 0x00 0x0000000f   and 0x0000000f
 0020: 0x15 0x00 0x04 0x00000002   jeq 2    true:0021 false:0025
 0021: 0x20 0x00 0x00 0x00000024   ld  $data[36]
 0022: 0x15 0x00 0x02 0x00000000   jeq 0    true:0023 false:0025
 0023: 0x20 0x00 0x00 0x00000020   ld  $data[32]
 0024: 0x15 0x04 0x00 0x00000003   jeq 3    true:0029 false:0025
 0025: 0x20 0x00 0x00 0x00000018   ld  $data[24]
 0026: 0x54 0x00 0x00 0x0000000f   and 0x0000000f
 0027: 0x15 0x01 0x00 0x00000001   jeq 1    true:0029 false:0028
 0028: 0x06 0x00 0x00 0x00050064   ret ERRNO(100)
 0029: 0x06 0x00 0x00 0x7fff0000   ret ALLOW
 0030: 0x06 0x00 0x00 0x00000000   ret KILL
```

**Comment by pcmoore** [comment]
I'm finding two things very confusing:
1. Why is the python generated BPF different from the native/C generated BPF?
2. The `_hsh_add()` code should still be checking the actual BPF instructions in the case of a hash collision (the `memcmp()`) so this *should* never happen, but it *does* happen ... why?

**Comment by drakenclimber** [comment]
I think the python bindings dependencies aren't quite right in the makefile.  I was able to get my python tests to pass by doing the following:

```
$ touch src/python/seccomp.pyx
$ make check-build

$ pushd tests
$ ./regression -m python -b 50-sim-hash_collision -s 1
=============== Tue Apr 16 17:15:06 MDT 2019 ===============
Regression Test Report ("regression -m python -b 50-sim-hash_collision -s 1")
 batch name: 50-sim-hash_collision
 test mode:  python
 test type:  bpf-sim
Test 50-sim-hash_collision%%001-00001 result:   SUCCESS
Regression Test Summary
 tests run: 1
 tests skipped: 0
 tests passed: 1
 tests failed: 0
 tests errored: 0
============================================================

$ popd
```

**Comment by pcmoore** [comment]
Okay, I'll believe that, and it makes sense why it works on Travis and "magically" started working on my system.  Let's merge this.

Merged into master via 234add8d8fc541d472332f5324b9af50ad9523bc and 7d530d309c894c4a3beaa78529821dd87611111b; merged into release-2.4 via 40758a140793733e8fdd416bff65a14f8c5d5836 and fef951a3e7f026bfcfc43191d2ed2074497b89dc.

**Pull request closed without merging**
